let questions = [
    [
        1,
        "Do you walk faster",
        "I'm faster",
        "I'm slower",
        "walk faster",
        "walk slower",
        5462,
        3682,
        1780
    ],
    [
        2,
        "Do you eat healthier food",
        "healthier",
        "less healthy",
        "eat healthier",
        "eat less healthy",
        6999,
        3314,
        3685
    ],
    [
        3,
        "Do you care more about the environment",
        "I care more",
        "I care less",
        "care more about the environment",
        "care less about the environment",
        7122,
        4469,
        2653
    ],
    [
        4,
        "Are you better at keeping your home tidy",
        "I'm better",
        "I'm worse",
        "are better at keeping their home tidy",
        "are worse at keeping their home tidy",
        7635,
        3123,
        4512
    ],
    [
        5,
        "Are you smarter",
        "I'm smarter",
        "I'm less smart ",
        "are smarter",
        "are less smart",
        7811,
        5956,
        1855
    ],
    [
        6,
        "Are your feet better looking",
        "they're better",
        "they're worse",
        "have better looking feet",
        "have worse looking feet",
        7647,
        3557,
        4090
    ],
    [
        7,
        "Are you a better listener",
        "I'm better",
        "I'm worse",
        "are a better listener",
        "are a worse listener",
        7722,
        4623,
        3099
    ],
    [
        8,
        "Are you more privileged",
        "I'm more",
        "I'm less",
        "are more privileged",
        "are less privileged",
        7758,
        5880,
        1878
    ],
    [
        9,
        "Do you smell better",
        "I smell better",
        "I smell worse",
        "smell better",
        "smell worse",
        7752,
        4099,
        3653
    ],
    [
        10,
        "Are you a better communicator",
        "I'm better",
        "I'm worse",
        "are a better communicator",
        "are a worse communicator",
        7838,
        4066,
        3772
    ],
    [
        11,
        "Are you better at washing up dishes",
        "I'm better",
        "I'm worse",
        "are better at washing up",
        "are worse at washing up",
        7679,
        3782,
        3897
    ],
    [
        12,
        "Are you more curious",
        "I'm more",
        "I'm less",
        "are more curious",
        "are less curious",
        7773,
        5844,
        1929
    ],
    [
        13,
        "Are you happier",
        "I'm happier",
        "I'm less happy",
        "are happier",
        "are less happy",
        7755,
        3943,
        3812
    ],
    [
        14,
        "Are you kinder",
        "I'm kinder",
        "I'm less kind",
        "are kinder",
        "are less kind",
        7076,
        4768,
        2308
    ],
    [
        15,
        "Do you have better ideas",
        "they're better",
        "they're worse",
        "have better ideas",
        "have worse ideas",
        7080,
        4519,
        2561
    ],
    [
        16,
        "Are you more conservative",
        "I'm more",
        "I'm less",
        "are more conservative",
        "are less conservative",
        7170,
        1790,
        5380
    ],
    [
        17,
        "Do you complain more",
        "I complain more",
        "I complain less",
        "complain more",
        "complain less",
        7905,
        3557,
        4348
    ],
    [
        18,
        "Do you give more to homeless people",
        "I give more",
        "I give less",
        "give more to homeless people",
        "give less to homeless people",
        6800,
        1617,
        5183
    ],
    [
        19,
        "Do you have a better music taste",
        "It's better",
        "It's worse",
        "have a better music taste",
        "have a worse music taste",
        7037,
        3677,
        3360
    ],
    [
        20,
        "Do you give better gifts",
        "they're better",
        "they're worse",
        "give better gifts",
        "give worse gifts",
        7536,
        3154,
        4382
    ],
    [
        21,
        "Are you a better friend",
        "I'm better",
        "I'm worse",
        "are a better friend",
        "are a worse friend",
        7807,
        3801,
        4006
    ],
    [
        22,
        "Are you more progressive",
        "I'm more",
        "I'm less",
        "are more progressive",
        "are less progressive",
        7534,
        5343,
        2191
    ],
    [
        23,
        "Are you better looking",
        "I'm better",
        "I'm worse",
        "are better looking",
        "are worse looking",
        7980,
        3999,
        3981
    ],
    [
        24,
        "Are you more interesting",
        "I'm more",
        "I'm less",
        "are more interesting",
        "are less interesting",
        7673,
        3710,
        3963
    ],
    [
        25,
        "Are you better at your work",
        "I'm better",
        "I'm worse",
        "are better at their work",
        "are worse at their work",
        7559,
        4742,
        2817
    ],
    [
        26,
        "Are you more ambitious",
        "I'm more",
        "I'm less",
        "are more ambitious",
        "are less ambitious",
        7765,
        3452,
        4313
    ],
    [
        27,
        "Are you more creative",
        "I'm more",
        "I'm less",
        "are more creative",
        "are less creative",
        7777,
        4009,
        3768
    ],
    [
        28,
        "Are you better at sex",
        "I'm better",
        "I'm worse",
        "are better at sex",
        "are worse at sex",
        5854,
        2594,
        3260
    ],
    [
        29,
        "Are you more patient",
        "I'm more",
        "I'm less",
        "are more patient",
        "are less patient",
        7578,
        4454,
        3124
    ],
    [
        30,
        "Do you have better dental hygiene",
        "better",
        "worse",
        "have better dental hygiene",
        "have worse dental hygiene",
        7224,
        3214,
        4010
    ],
    [
        31,
        "Do you procrastinate more",
        "more",
        "less",
        "procrastinate more",
        "procrastinate less",
        6992,
        4837,
        2155
    ],
    [
        32,
        "Are you a better driver",
        "I'm better",
        "I'm worse",
        "are a better driver",
        "are a worse driver",
        7058,
        4223,
        2835
    ],
    [
        33,
        "Did you have a better childhood",
        "it was better",
        "it was worse",
        "had a better childhood",
        "had a worse childhood",
        6946,
        4591,
        2355
    ],
    [
        34,
        "Are you a better hugger",
        "I'm better",
        "I'm worse",
        "are a better hugger",
        "are a worse hugger",
        6843,
        3577,
        3266
    ],
    [
        35,
        "Are you funnier",
        "I'm funnier",
        "I'm less funny",
        "are funnier",
        "are less funny",
        6835,
        4042,
        2793
    ],
    [
        36,
        "Are you better at maths",
        "I'm better",
        "I'm worse",
        "are better at maths",
        "are worse at maths",
        7079,
        4296,
        2783
    ],
    [
        37,
        "Do you spend more time on your phone",
        "more",
        "less",
        "spend more time on their phone",
        "spend less time on their phone",
        7116,
        3803,
        3313
    ],
    [
        38,
        "Are you more narcissistic",
        "I'm more",
        "I'm less",
        "are more narcissistic",
        "are less narcissistic",
        7189,
        2801,
        4388
    ],
    [
        39,
        "Are you more stereotypically your gender",
        "I'm more",
        "I'm less",
        "are more stereotypically their gender",
        "are less stereotypically their gender",
        7271,
        2629,
        4642
    ],
    [
        40,
        "Do you have a better memory",
        "it's better",
        "it's worse",
        "have a better memory",
        "have a worse memory",
        7211,
        3427,
        3784
    ],
    [
        41,
        "Are you more humble",
        "I'm more",
        "I'm less",
        "are more humble",
        "are less humble",
        7054,
        3942,
        3112
    ],
    [
        42,
        "Are you better at cooking",
        "I'm better",
        "I'm worse",
        "are better at cooking",
        "are worse at cooking",
        6687,
        3419,
        3268
    ],
    [
        43,
        "Do you change your bed sheets more",
        "more",
        "less",
        "change their bed sheets more",
        "change their bed sheets less",
        7064,
        2186,
        4878
    ],
    [
        44,
        "Do you have more common sense",
        "I have more",
        "I have less",
        "have more common sense",
        "have less common sense",
        6934,
        5105,
        1829
    ],
    [
        45,
        "Are more confident ",
        "I'm more",
        "I'm less",
        "are more confident",
        "are less confident",
        7074,
        3154,
        3920
    ],
    [
        46,
        "Do you exercise more",
        "more",
        "less",
        "exercise more",
        "exercise less",
        6973,
        2624,
        4349
    ],
    [
        47,
        "Do you read more",
        "more",
        "less",
        "read more",
        "read less",
        6768,
        2840,
        3928
    ],
    [
        48,
        "Do you sleep more",
        "more",
        "less",
        "sleep more",
        "sleep less",
        7023,
        3183,
        3840
    ],
    [
        49,
        "Do you have more friends ",
        "I have more",
        "I have fewer",
        "have more friends",
        "have fewer friends",
        6171,
        1650,
        4521
    ],
    [
        50,
        "Are you healthier",
        "I'm healthier",
        "I'm less healthy",
        "are healthier",
        "are less healthy",
        6861,
        3546,
        3315
    ],
    [
        51,
        "Are you more religious",
        "I'm more",
        "I'm less",
        "are more religious",
        "are less religious",
        6950,
        1404,
        5546
    ],
    [
        52,
        "Are you more optimistic",
        "I'm more",
        "I'm less",
        "are more optimistic",
        "are less optimistic",
        4437,
        2166,
        2271
    ],
    [
        53,
        "Are you more socialist",
        "I'm more",
        "I'm less",
        "are more socialist",
        "are less socialist",
        468,
        250,
        218
    ],
    [
        54,
        "Do you dress better",
        "better",
        "worse",
        "dress better",
        "dress worse",
        473,
        166,
        307
    ],
    [
        55,
        "Do you have better handwriting",
        "better",
        "worse",
        "have better handwriting",
        "have worse handwriting",
        454,
        156,
        298
    ],
    [
        56,
        "Do you have sex more often",
        "more",
        "less",
        "have sex more often",
        "have sex less often",
        496,
        80,
        416
    ],
    [
        57,
        "Are you wealthier",
        "I'm wealthier",
        "I'm less wealthy",
        "are wealthier",
        "are less wealthy",
        482,
        284,
        198
    ],
    [
        58,
        "Are you a better partner ",
        "I'm better",
        "I'm worse",
        "are a better partner ",
        "are a worse partner ",
        497,
        286,
        211
    ],
    [
        59,
        "Are you more honest",
        "I'm more",
        "I'm less",
        "are more honest",
        "are less honest",
        483,
        365,
        118
    ],
    [
        60,
        "Are you more empathetic",
        "I'm more",
        "I'm less",
        "are more empathetic",
        "are less empathetic",
        447,
        311,
        136
    ],
    [
        61,
        "Are you braver",
        "I'm braver",
        "I'm less brave",
        "are braver",
        "are less brave",
        468,
        192,
        276
    ],
    [
        62,
        "Do you drink more water",
        "I drink more",
        "I drink less",
        "drink more water",
        "drink less water",
        482,
        225,
        257
    ],
    [
        63,
        "Do you worry more",
        "more",
        "less",
        "worry more",
        "worry less",
        487,
        327,
        160
    ],
    [
        64,
        "Are you more punctual",
        "I'm more",
        "I'm less",
        "are more punctual",
        "are less punctual",
        513,
        287,
        226
    ],
    [
        65,
        "Do you use social media more",
        "more",
        "less",
        "use social media more",
        "use social media less",
        496,
        132,
        364
    ],
    [
        66,
        "Are you lazier",
        "I'm lazier",
        "I'm less lazy",
        "are lazier",
        "are less lazy",
        495,
        281,
        214
    ],
    [
        67,
        "Are you more extroverted",
        "I'm more",
        "I'm less",
        "are more extroverted",
        "are less extroverted",
        509,
        124,
        385
    ],
    [
        68,
        "Are you more loved",
        "I'm more",
        "I'm less",
        "are more loved",
        "are less loved",
        474,
        245,
        229
    ],
    [
        69,
        "Are you more annoying",
        "I'm more",
        "I'm less",
        "are more annoying",
        "are less annoying",
        477,
        205,
        272
    ],
    [
        70,
        "Do you cry more",
        "more",
        "less",
        "cry more",
        "cry less",
        486,
        169,
        317
    ],
    [
        71,
        "Are you more perceptive",
        "I'm more",
        "I'm less",
        "are more perceptive",
        "are less perceptive",
        457,
        337,
        120
    ],
    [
        72,
        "Are you more sensitive",
        "I'm more",
        "I'm less",
        "are more sensitive",
        "are less sensitive",
        501,
        318,
        183
    ],
    [
        73,
        "Are you more fulfilled",
        "I'm more",
        "I'm less",
        "are more fulfilled",
        "are less fulfilled",
        445,
        213,
        232
    ],
    [
        74,
        "Are you more important",
        "I'm more",
        "I'm less",
        "are more important",
        "are less important",
        481,
        159,
        322
    ]
]